services:
  - type: web
    name: goldenai-signal
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
